//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int id { get; set; }
        public int Bookid { get; set; }
        public int Studentid { get; set; }
        public System.DateTime dateOfBorrow { get; set; }
        public Nullable<System.DateTime> dateOfReturn { get; set; }
        public Nullable<long> Money { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
