//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int id { get; set; }
        public string pcode { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> auth_id { get; set; }
    }
}
